# Generated by Django 6.1.1 on 2026-09-25 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('iin', models.CharField(max_length=12)),
                ('encrypted_password', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('consent_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PlatonusConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.TextField(editable=False)),
                ('consent_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=32)),
                ('last_verified_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platonus_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
