# Generated by Django 6.1.1 on 2026-09-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration_platonusconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gpa_source', models.CharField(blank=True, max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='student_photos/')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('gpa_updated_at', models.DateTimeField(blank=True, null=True)),
                ('photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=16)),
                ('sync_message', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
