# Generated by Django 6.1.1 on 2026-09-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.SmallIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=16)),
                ('sync_message', models.TextField(blank=True)),
                ('sync_token', models.UUIDField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'term'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'term'), name='unique_journal_user_period')],
            },
        ),
    ]
