# Generated by Django 6.1.1 on 2026-09-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Порядок в журнале')),
                ('source_name', models.TextField(verbose_name='Название из Platonus')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='journal.journalsnapshot', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Дисциплина студента',
                'verbose_name_plural': 'Дисциплины студентов',
                'ordering': ['snapshot_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='JournalLessonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Порядок строки')),
                ('stream_label', models.TextField(blank=True, verbose_name='Учебный поток из Platonus')),
                ('teacher_label', models.TextField(blank=True, verbose_name='Подпись преподавателя из Platonus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_rows', to='journal.journalsubject', verbose_name='Дисциплина студента')),
            ],
            options={
                'verbose_name': 'Строка занятий',
                'verbose_name_plural': 'Строки занятий',
                'ordering': ['subject_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='JournalSubjectValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=255, verbose_name='Колонка из Platonus')),
                ('column_position', models.PositiveIntegerField(verbose_name='Порядок колонки')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Исходное значение')),
                ('value_kind', models.CharField(choices=[('number', 'Число'), ('empty', 'Пусто'), ('marker', 'Обозначение'), ('text', 'Текст')], max_length=16, verbose_name='Тип значения')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Числовое значение')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='journal.journalsubject', verbose_name='Дисциплина студента')),
            ],
            options={
                'verbose_name': 'Общий показатель дисциплины',
                'verbose_name_plural': 'Общие показатели дисциплин',
                'ordering': ['subject_id', 'column_position'],
            },
        ),
        migrations.CreateModel(
            name='JournalRowValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=255, verbose_name='Колонка из Platonus')),
                ('column_position', models.PositiveIntegerField(verbose_name='Порядок колонки')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Исходное значение')),
                ('value_kind', models.CharField(choices=[('number', 'Число'), ('empty', 'Пусто'), ('marker', 'Обозначение'), ('text', 'Текст')], max_length=16, verbose_name='Тип значения')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Числовое значение')),
                ('lesson_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='journal.journallessonrow', verbose_name='Строка занятий')),
            ],
            options={
                'verbose_name': 'Значение строки занятий',
                'verbose_name_plural': 'Значения строк занятий',
                'ordering': ['lesson_row_id', 'column_position'],
                'constraints': [models.UniqueConstraint(fields=('lesson_row', 'source_column'), name='unique_row_value_column'), models.CheckConstraint(condition=models.Q(models.Q(('numeric_value__isnull', False), ('value_kind', 'number')), models.Q(('numeric_value__isnull', True), ('value_kind__in', ['empty', 'marker', 'text'])), _connector='OR'), name='valid_row_value_kind_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='journalsubject',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='unique_subject_snapshot_position'),
        ),
        migrations.AddConstraint(
            model_name='journallessonrow',
            constraint=models.UniqueConstraint(fields=('subject', 'position'), name='unique_lesson_subject_position'),
        ),
        migrations.AddConstraint(
            model_name='journalsubjectvalue',
            constraint=models.UniqueConstraint(fields=('subject', 'source_column'), name='unique_subject_value_column'),
        ),
        migrations.AddConstraint(
            model_name='journalsubjectvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('numeric_value__isnull', False), ('value_kind', 'number')), models.Q(('numeric_value__isnull', True), ('value_kind__in', ['empty', 'marker', 'text'])), _connector='OR'), name='valid_subject_value_kind_number'),
        ),
    ]
