# Generated by Django 6.1.1 on 2026-10-01 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalsubject_journallessonrow_journalsubjectvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('token', models.UUIDField(editable=False, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_import', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Импорт журналов',
                'verbose_name_plural': 'Импорты журналов',
            },
        ),
    ]
